### ISSUE TITLE
Cant set python path in the fife installer.

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fife-windows-sdk#3]
Cant set python path in the fife installer.

![installer-bug](https://cloud.githubusercontent.com/assets/1757651/20464088/2ee22bea-af41-11e6-9d53-608f28a9cc04.jpg)

i cant type anything into the lines there :(

**Comment by jakoch** [comment]
That installer generated by the python tools is so retro... 👎 
They rely on path detection to find Python a bit too much and 
it's also not possible to script the installer to do a silent install or pass the path from the outside.
When Python isn't found, you can't even set the path manually.. which is clearly a bug.
Anyway...

---

One solution could be to add the path to python to the environment PATH variable,
e.g.: `C:\Python27\;C:\Python27\Scripts\`, before running the installer inside the `[Run]` section.
That should guide the installer to find Python, so that the user can select it and proceed with installation.

**Comment by LinuxDonald** [comment]
What about to take the non installer version of fife and take the zipped package and extract it with the sdk installer and set path?

**Comment by jakoch** [comment]
That should work, too.

**Comment by LinuxDonald** [comment]
I think it's the easiest way and maybe the best one :-)

**Comment by LinuxDonald** [comment]
@jakoch i have started with some work for it: https://github.com/fifengine/fife-windows-sdk/pull/4

**Comment by prock-fife** [comment]
> That installer generated by the python tools is so retro... :-1: 

Very much agreed.  When I originally started using it way back when it was retro back then as well :(

It also suffered from the problem of not being able to detect python in all cases.  I decided to live with it back then.

Not ideal but is there a way we can have the user download the python module and install it themselves into their python disto?  e.g.  python setup.py install

Or maybe we can have the installer run that command?  If it doesn't find python it could fail, give a nice message telling the user to add python to their PATH and exit gracefully.

**Comment by jakoch** [comment]
> Not ideal but is there a way we can have the user download the python module and install it themselves into their python disto? e.g. `python setup.py install`

Providing a list with install instructions isn't ideal. I want to avoid laying out steps for users as much as possible. The installer should bring the needed components out-of-the-box: so that users can start developing right away. I think we should only exclude components like Visual C / IDE.  Because editors are personal taste anyway and MSVC has to many system dependencies to automate an installation. 
We could, of course, include the MSVC webinstaller and trigger it, if it isn't installed already. 
That would be another feature for our installer. But, let's solve the Python installer issue first.

To make it work: we need to figure out, how to set the path to python.

**Comment by LinuxDonald** [comment]
@jakoch the .msi version of the installer for fife works much better https://ci.appveyor.com/project/LinuxDonald/fifengine/build/dev-a83aeb0/job/itaf98ov73qne20d/artifacts

https://github.com/fifengine/fifengine/tree/test but needs fine tuning for the version number.

**Comment by LinuxDonald** [comment]
@jakoch maybe we can use the same version number string as for the sdk? For example fife-0.4.0 version instant of the dev-git version?

**Comment by jakoch** [comment]
I think we patched `setup.py` in fifengine repo to accept a version number from the outside.
But seems the python MSI installer builder isn't able to handle the `dev-hash` part correctly and only accepts a `x.y.z` versioning scheme. 

- You could simply set a constant in appveyor.yml and pass it to setup.py, instead of the automatic dev-hash versioning.
- Or pass it to setup.py manually
- Or maybe it works with the default version number in `setup.py`, see https://github.com/fifengine/fifengine/blob/master/setup.py#L51
  If you don't set a version the default version from setup.py should be used internally and also for the filename - if that doesn't happen.. well, then it's just another python installer bug.

**Comment by LinuxDonald** [comment]
See https://github.com/fifengine/fife-windows-sdk/issues/6 for the python PATH problem.
